#!/usr/bin/env bash
# printing 'Best School' ten times using while loop but printing 'bad luck' on the 4th line and 'good luck' on the 8th line

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"	  
  else 
    echo "Best School"
  fi
  (( count++ ))
done

